### ISSUE TITLE
amd loading for plugins

### ISSUE THREAD

**Issue by delrosario** [quirkey/sammy#152] opened 2012-08-12 10:45 UTC
Been using sammy for a while now ever since you gave the presentation at socal.js and been happy with it.

I saw that sammy.js main file is amd compatible so i tried to do:

define(['jquery', 'sammy', 'sammy.title'], function ($, Sammy) {
  console.log('loaded routers);
  return Sammy('#main', function () {
    this.use(Sammy.Title);
  });
});

The problem is the plugins are not amd compatible.

So using requirejs i added sammy.title to the shim configuration:

require.config({
  shim: {
    'sammy.title': ['jquery', 'sammy']
  }
});

The problem is Sammy is an undeclared variable in sammy.title.js giving the error: ReferenceError: Sammy is not defined

You either have to declare Sammy in the plugin properly:

(function($) {
var Sammy = window.Sammy || {};
//rest of the code
window.Sammy = Sammy;
}(window.jQuery));

or do what I did, which is to modify my local copy of sammy and wrap it in the amd plugin pattern:

(function (factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery', 'sammy'], factory);
  } else {
    factory(jQuery, Sammy);
  }
}(function($, Sammy) {
  // put the plugin code here
}));

The main sammy file is already doing this and would be great if we can do it for the rest of the plugins.

Thanks;

-del

**Comment by endor** [comment] 2012-08-13 06:20
hey del. would you by any chance have the time to implement this and send a pull request? that would be really helpful.

**Comment by delrosario** [comment] 2012-08-13 09:21
Will do sometime this week. It's a good chance for me to learn how to contributing to public repositories XD.

**Comment by endor** [comment] 2012-09-26 10:56
This is a duplicate of #154.

**Closed as completed by endor** 2012-09-26 10:56 UTC
