### ISSUE TITLE
.load() issue when calling a sinatra json route (cors)

### ISSUE THREAD

**Issue by Darcbar** [quirkey/sammy#145] opened 2012-06-08 16:17 UTC
I am having trouble getting the .load() method to work with a call to a sinatra api located on a different domain using Cross-Origin Resource Sharing, when calling:

```
 $.ajax({
 url: 'http://localhost:4567/posts',
      dataType: 'json',
      success: function(items) {
             $.each(items, function(i, item) {
                  context.log(item.title);
             });
      }
  });
```

... all is well, and the item/post title is displayed in firebug. But when using .load():

```
 this.load('http://localhost:4567/posts')

 .then(function(items) {
       $.each(items, function(i, item) {
            context.log(item.title);
       });
 });
```

...the response seems to return the json object according to firebug but the console shows: http://pastie.org/4051256

If instead of logging I attempt to insert the json data into templates:

```
 this.load('http://localhost:4567/posts')
 .then(function(items) {
      $.each(items, function(i, item) {
           context.render('tmpl/item.mustache', {item: item})
           .appendTo(context.$element());
      });
 });
```

... bearing in mind the return is a json array of only three posts, the template is getting loaded successfully but without any data injected and also its being rendered the same amount of times as the number of 'undefined' lines in the above pastie??

**Comment by endor** [comment] 2012-06-28 13:31
okay, so I tried to reproduce your problem and am failing. first of all.. is it relevant that the whole thing is cross domain or do you have the same problem when running it all locally? I created a basic sinatra app that returns [{title: 'abc'}, {title: 'def'}, {title: 'ghi'}].to_json. is that similar to what you're doing? I don't see any errors when using this.load and console.log. Please bear in mind though that this will only work if you JSON parse the response first. Rendering it in templates works also fine, although I am not sure why you would loop through the items instead of just sending the whole thing into the template. also.. which mustache.js version do you use?

**Comment by Darcbar** [comment] 2012-06-28 15:18
Hi endor

Thanks for your response, the problem was I hadn't parsed the response so the issue is sorted, sorry for the time waste

I'm not sure what you mean by `sending the whole thing into the template` instead of looping, I'm using the sammy store tutorial which loops through the json file. How would you send the whole thing to a template?

**Comment by endor** [comment] 2012-06-29 07:53
I guess it doesn't really matter how you do it. I would probably do it something like this:

```
    this.load('http://localhost:4567/posts')
        .then(function(items) {
          context.render('template.mustache', {items: JSON.parse(items)})
                 .appendTo($('#result'));              
        });

    {{#items}}
      <li>{{title}}</li>
    {{/items}}
```

So I'll close the issue now, since it's not valid anymore.

**Closed as completed by endor** 2012-06-29 07:53 UTC
