### ISSUE TITLE
Exceptions handles within sammy.

### ISSUE THREAD

**Issue by raananraz** [quirkey/sammy#169] opened 2012-11-07 14:46 UTC
It is possible to remove the error handling in sammy?
This causes a lot of problems debugging since sammy handles the exception.

Thank you!

**Comment by rikkert** [comment] 2012-12-17 09:21
Instead you can consider turning on any of the following options:

``` javascript
// local development only!
this.debug = true;
this.disable_push_state = true;
this.raise_errors = true;
```

Officiously you are looking for the option: **raise_errors**.
IMO this issue can be closed.

**Comment by endor** [comment] 2012-12-17 09:39
@raananraz does that solve your problem? if yes, please close. if no, please explain what exactly the problem is, so we can find a solution.

**Comment by raananraz** [comment] 2012-12-17 13:08
the raise_errors worked great! still getting console output on: "runRoute"

below is my code.
app.disable_push_state = true;
app.raise_errors = true;
app.debug = false;
app.run("#/page/main/show");

**Comment by endor** [comment] 2012-12-18 08:32
@raananraz that's fixed in the most current file (just not in the minified version yet).

**Closed as completed by endor** 2012-12-18 08:32 UTC

**Comment by raananraz** [comment] 2012-12-18 13:51
It works! I created a minified version myself for now. thx! :)
